name: prototype_presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  convex_bottom_bar: 3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: 2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: 2.0.0
  geocoding: 2.1.0
  geolocator: 9.0.2
  get: 4.6.5
  image_picker: 0.8.7+5
  intl: 0.18.1
  open_file: ^3.3.0
  path_provider: ^2.1.1
  pdf: ^3.10.4
  syncfusion_flutter_datepicker: ^21.1.39

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
